<?php

/**
 * @file
 * Main file for linkit_pikcer module.
 */

/**
 * Implements hook_form_alter().
 */
function linkit_picker_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == "linkit_dashboard_form") {
      if (isset($form['#suffix'])) {
        $form['#suffix'] .= linkit_picker_dashboard_filter();
      }
      else {
        $form['#suffix'] = linkit_picker_dashboard_filter();
      }
  }
}

function linkit_picker_dashboard_filter() {

   return _linkit_picker_render_container(array('linkit_picker_node', 'linkit_picker_term', 'linkit_picker_user'));
}

/**
 * Return all the views that should be used in the container.
 */
function _linkit_picker_render_container($views) {
  $container = array(
    '#type' => 'container',
    '#attributes' => array('class' => array('linkit-picker-container'), 'id' => 'linkit-picker-container'),
  );

  drupal_add_css(drupal_get_path('module', 'linkit_picker') . '/linkit_picker.css');
  drupal_add_js(drupal_get_path('module', 'linkit_picker') . '/linkit_picker.js');

  foreach ($views as $viewname) {
    $view = _linkit_picker_get_view($viewname);
    $container['browser_wrapper'][$viewname] = array(
      '#type' => 'link',
      '#title' => $view->get_title(),
      '#attributes' => array('class' => array('linkit-picker-button'), 'data-viewname' => $viewname),
    );

    $container[$viewname] = array(
      '#type' => 'container',
      '#attributes' => array('class' => array('view-container', 'view-linkit-picker-' . $viewname)),
    );
    $container[$viewname]['view'] = array(
      '#markup' => $view->preview('default'),
    );
  }

  return drupal_render($container);
}

/**
 * Implements hook_views_api().
 */
function linkit_picker_views_api() {
  return array(
      'api' => 3,
      'path' => drupal_get_path('module', 'linkit_picker') . '/includes',
  );
}


function _linkit_picker_get_view($viewname) {
  $view = views_get_view($viewname);
  if ($view && $view->access('default')) {
    return $view;
  }
  else {
    return NULL;
  }

}
